# Model arguments
model_name_or_path: LumiOpen/Poro-34B
torch_dtype: bfloat16
max_seq_length: 2048

# LoRA arguments
load_in_4bit: false
use_peft: false
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- query_key_value
- dense
- dense_4h_to_h
- dense_h_to_4h
- lm_head


#Data arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
#chat_template: "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
#dataset_mixer:
#  /scratch/project_462000319/finetuning_data/SFTTrainer_format/dolly-fi: 1.0 #15k rows
#  /scratch/project_462000319/finetuning_data/SFTTrainer_format/oasst1-fi: 1.0 #20k rows
#  /scratch/project_462000319/finetuning_data/SFTTrainer_format/lima-fi: 1.0 #800 rows
#  /scratch/project_462000319/finetuning_data/SFTTrainer_format/oasst2: 1.0
#  /scratch/project_462000319/finetuning_data/SFTTrainer_format/turku-paraphrase: 1.0
#  /scratch/project_462000319/finetuning_data/SFTTrainer_format/Capybara-fi-deepl: 1.0
#  /scratch/project_462000319/finetuning_data/SFTTrainer_format/ultrachat_16k_fi_deepl: 0.5
#  /scratch/project_462000319/finetuning_data/SFTTrainer_format/argilla/10k_prompts_ranked_mistral_large_responses: 1.0 #5098 examples
#dataset_splits:
#- train
#- test
packing: true
dataset_text_field: text
preprocessing_num_workers: 7
append_concat_token: false
add_special_tokens: false


#TrainingArguments
bf16: true
do_eval: true
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-5 #From OpenAssistant configs on 30b+ models
log_level: info
log_on_each_node: false
logging_steps: 10
evaluation_strategy: steps
eval_steps: 500
logging_strategy: steps
lr_scheduler_type: constant_with_warmup
max_grad_norm: 2.0 #From OpenAssistant configs on 30b+ models
max_steps: -1 #I dont know why this is -1
num_train_epochs: 3
output_dir: /scratch/project_462000241/villekom/models/temp/debug
overwrite_output_dir: true #True as it's only for debugging
per_device_eval_batch_size: 4
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1