# Model arguments
model_name_or_path: LumiOpen/Poro-34B
torch_dtype: bfloat16
max_seq_length: 2048

# LoRA arguments
load_in_4bit: false
use_peft: false
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- query_key_value
- dense
- dense_4h_to_h
- dense_h_to_4h
- lm_head


#Data arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
#chat_template: "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
packing: true
dataset_text_field: text
preprocessing_num_workers: 7
append_concat_token: false
add_special_tokens: false


#TrainingArguments
bf16: true
do_eval: true
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-5 
log_level: info
log_on_each_node: false
logging_steps: 10
evaluation_strategy: steps
eval_steps: 500
logging_strategy: steps
lr_scheduler_type: cosine
max_grad_norm: 2.0
max_steps: -1
num_train_epochs: 3
output_dir: /scratch/project_462000558/TurkuNLP_workshop
per_device_eval_batch_size: 4
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1